[project]
name = "PlanckConv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "notebook>=7.6.1",
    "pixell>=0.31.10",
    "ruff>=0.15.21",
    "smarties @ git+https://github.com/camilledemay/smarties-beam-convolution",
    "ty>=0.0.63",
]

[tool.hatch.metadata]
allow-direct-references = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
